# Generated by Django 5.0.3 on 2024-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='brand',
            name='picture',
            field=models.ImageField(upload_to='brands'),
        ),
    ]
